RSU REST API
CDOT-CV/RSU_Management pull request #33
Opened 2021-11-30 23:20 UTC by drewjj

This includes:
- New RSU REST API docker image
- Python REST API script that validates arguments before running scripts
- Snmpwalk script to be accessed through the REST API

Not included:
- I forgot we have some unit tests in this repository. I can add unit tests for these scripts going forward if that is wanted
- Snmpset support is still not supported. The original goal was to get the current SNMP configurations visible so I focused on snmpwalk

2021-11-30 23:39 UTC, drewjj commented
Here is example output from the snmpwalk for 172.16.28.200

```
{
  'snmpwalk': {
    '1': {
      'Message Type': 'BSM',
      'IP': '10.235.1.3',
      'Port': 46800,
      'Protocol': 'UDP',
      'RSSI': -100,
      'Frequency': 1,
      'Start DateTime': '1970-12-31 17:00',
      'End DateTime': '2036-12-31 17:00',
      'Forwarding': 'On',
      'Config Active': 'Enabled'
    },
    '2': {
      'Message Type': 'BSM',
      'IP': '10.14.137.229',
      'Port': 8087,
      'Protocol': 'UDP',
      'RSSI': -100,
      'Frequency': 1,
      'Start DateTime': '1970-12-31 17:00',
      'End DateTime': '2036-12-31 17:00',
      'Forwarding': 'On',
      'Config Active': 'Enabled'
    },
    '3': {
      'Message Type': 'BSM',
      'IP': '10.235.1.36',
      'Port': 46800,
      'Protocol': 'UDP',
      'RSSI': -100,
      'Frequency': 1,
      'Start DateTime': '1970-12-31 17:00',
      'End DateTime': '2036-12-31 17:00',
      'Forwarding': 'On',
      'Config Active': 'Enabled'
    },
    '4': {
      'Message Type': 'BSM',
      'IP': '10.235.1.66',
      'Port': 46800,
      'Protocol': 'UDP',
      'RSSI': -100,
      'Frequency': 1,
      'Start DateTime': '1970-12-31 17:00',
      'End DateTime': '2036-12-31 17:00',
      'Forwarding': 'On',
      'Config Active': 'Enabled'
    }
  }
}
```

2021-12-03 17:39 UTC, payneBrandon commented
Let's add in some tests to show what the snmpwalk.py script is doing, and how it will handle failed walk attempts, etc.

2021-12-03 17:44 UTC, payneBrandon requested changes
Looking good, just a couple things to note. Let's also restructure this a bit, maybe adding the txt files under a "resources" directory, code files under "src" or similar. We could also rename the "automation" directory to be more specific like "snmp_automation" so we know what to expect in here.

2021-12-03 17:44 UTC, payneBrandon commented on automation/snmpwalk.py
> +def get(rsuip, road):
Can we add some comments in here explaining what we expect to see in each part of the process? For instance after we run the snmpwalk command, what are we expecting to be returned? What format should the snmp_config returned object be in?

2021-12-03 17:44 UTC, payneBrandon commented on automation/snmpwalk.py
> +	if len(output) < 10:
Would we get an output up to 10 that would be failed? Let's explain this a bit with an example, or explanation of why up to 10.

2022-01-31 04:43 UTC, drewjj commented on automation/snmpwalk.py
> +def get(rsuip, road):
I may have addressed this

2022-01-31 04:43 UTC, drewjj commented on automation/snmpwalk.py
> +	if len(output) < 10:
Addressed with comment in the script

2022-01-31 04:44 UTC, drewjj commented
Added a new README and re-organize the automation directory

2022-02-01 20:17 UTC, payneBrandon commented on rsu_automation/README.md
> +The RSU Automation docker image allows for a front end application to interface with RSUs over a REST API to read and configure message forwarding settings over SNMP. Future features will be added to
Just a note, the "J2735 message deployments" at the end here will likely go through the ODE since it has the ability to encode and sign those message sets. Or are you thinking of a test message that is already encoded/signed and we would expand this library to push those out?

2022-02-01 20:27 UTC, payneBrandon commented on rsu_automation/README.md
> +- Message forwarding configurations over SNMP *(Supporting RSUs utilizing SNMP RSU 4.1 spec for message forwarding configuration)*
Can we link to a location the SNMP RSU 4.1 spec lives for users to look up? I'm not sure if the spec is open source/available or not but if not we can just link to where they can purchase it.

2022-02-01 20:29 UTC, payneBrandon commented on rsu_automation/Dockerfile
> +FROM gcr.io/google-appengine/python
Well that's a handy starting image!

2022-02-01 20:33 UTC, payneBrandon commented on rsu_automation/Dockerfile
> +RUN pip3 install flask
For these pip requirements, would it make sense to add them to a `requirements.txt`, copy over that file and run `pip install -r ./requirements.txt`? That way we wouldn't have to change the Dockerfile in the future and for users hitting it locally they'd know what packages to install.

2022-02-01 21:20 UTC, drewjj commented on rsu_automation/README.md
> +The RSU Automation docker image allows for a front end application to interface with RSUs over a REST API to read and configure message forwarding settings over SNMP. Future features will be added to
Wasn't really certain what features we were implementing through here to be honest. Although the ODE doesn't actually push those out over SNMP to RSUs does it?

2022-02-01 21:20 UTC, drewjj commented on rsu_automation/README.md
> +- Message forwarding configurations over SNMP *(Supporting RSUs utilizing SNMP RSU 4.1 spec for message forwarding configuration)*
I have no idea. I will ask Tony.

2022-02-01 21:21 UTC, drewjj commented on rsu_automation/Dockerfile
> +RUN pip3 install flask
yeah, we could do that

2022-02-01 21:31 UTC, payneBrandon commented on rsu_automation/README.md
> +The RSU Automation docker image allows for a front end application to interface with RSUs over a REST API to read and configure message forwarding settings over SNMP. Future features will be added to
It does! It uses a 3rd party SNMP library to do it, and has a few issues. I don't think it's set up to push MAP messages, but that would be a good place for us to put that functionality to keep it centralized.

2022-02-02 15:52 UTC, payneBrandon commented on rsu_automation/src/snmpwalk.py
> +		prop, raw_value = line.strip().split(' = ')
We talked about this yesterday,  but wanted to pop it in here as well. Let's get a few comments in this section so we know what is supposed to be happening in here.

2022-02-02 15:53 UTC, payneBrandon requested changes
Just the one comment, otherwise looking good!

2022-02-07 18:02 UTC, drewjj commented on rsu_automation/src/snmpwalk.py
> +		prop, raw_value = line.strip().split(' = ')
addressed

2022-02-07 18:03 UTC, drewjj commented on rsu_automation/README.md
> +- Message forwarding configurations over SNMP *(Supporting RSUs utilizing SNMP RSU 4.1 spec for message forwarding configuration)*
it is available somewhere for free, I have no idea where though

2022-02-07 18:25 UTC, drewjj commented on rsu_automation/Dockerfile
> +RUN pip3 install flask
Addressed and tested

2022-02-08 00:38 UTC, drewjj commented on rsu_automation/README.md
> +- Message forwarding configurations over SNMP *(Supporting RSUs utilizing SNMP RSU 4.1 spec for message forwarding configuration)*
addressed

2022-02-08 15:24 UTC, payneBrandon approved these changes
Looks good!

2022-02-08 15:24 UTC, merged