RSU Daily Count Emails
CDOT-CV/RSU_Management pull request #35
Opened 2022-01-27 15:51 UTC by drewjj

Includes a cloud function script and requirements file for deployment in GCP to send out a series of emails to different recipients with a table of yesterday's J2735 message counts.

Supports
- BSM
- SPaT
- MAP
- SSM
- SRM

2022-01-28 16:31 UTC, payneBrandon commented
Can we get a brief README in here to describe the purpose and any required configuration?

2022-01-28 21:43 UTC, drewjj commented
> Can we get a brief README in here to describe the purpose and any required configuration?

I have now made the README, feel free to check it out and let me know if you would like to see anything added.

2022-02-02 18:56 UTC, payneBrandon requested changes
Just a couple comments. Looking good!

2022-02-02 18:56 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +def query_table(table, message_type):
By separating out the queries for each type like this we have one query to get the RSUs, then a query per type in and query per type out. That gives us 11 hits to the database. Would it be possible to instead have two hits (one in and one out) to the database running something like the following query:

`SELECT RSU, Road, Type, SUM(Count) as Count
        FROM {{table}} 
        WHERE Date >= {{yesterday}}
        AND Date < {{today}}
        GROUP BY RSU, Road, Type
        ORDER BY Road, RSU, Type`

This would return a list of all RSUs with counts for each type. Then we could loop over those returned items in the query to generate the table in the email.

2022-02-03 21:36 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +  return ("Emails successfully sent", 200)
This return code serves no actual purpose. The scheduled task doesn't even listen to the response it gets. This was more for my own testing of it when I run it manually. We could have this return a proper value based on what happens but I didn't think it worth the effort.

2022-02-03 21:36 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +def query_table(table, message_type):
This could probably be better optimized. I guess I wasn't thinking about that. Good point. This might require the whole section of this code to be reworked a little bit. I guess I better get to it.

2022-02-03 21:36 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +  start = datetime.strftime(datetime.now() - timedelta(1), '%Y-%m-%d 00:00:00')
We could keep passing the values down but that seems a little weird to me. I will see about making them global variables.

2022-02-03 21:36 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +  return ("Emails successfully sent", 200)
Oh, and returning a 500 happens naturally thanks to cloud functions. So unless we want specific messages to be returned it wouldn't be too useful in my opinion.

2022-02-03 22:13 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +  start = datetime.strftime(datetime.now() - timedelta(1), '%Y-%m-%d 00:00:00')
Addressed, I did end up making them arguments to pass down because it makes sense when I thought about it

2022-02-03 22:13 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +def query_table(table, message_type):
I have done exactly this, addressed

2022-02-03 22:14 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +  return ("Emails successfully sent", 200)
I adjusted the regular return message to make is seem less deceptive if it does end up failing without throwing a 500

2022-02-07 17:07 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +def query_table(table, message_type):
I like how this is flowing now, very nice!

2022-02-07 17:08 UTC, payneBrandon approved these changes
Looks good to me!

2022-02-07 17:08 UTC, merged