Fixed missing zabbix data bug
CDOT-CV/RSU_Management pull request #36
Opened 2022-02-02 23:49 UTC by mwodahl

Added environment variables to App.js
Created functions in Map.js to handle errors when RSU data is missing to prevent app from crashing.

2022-02-07 16:58 UTC, payneBrandon requested changes
A couple comments, but looking good!

2022-02-07 16:58 UTC, payneBrandon commented on cdot-web-app/src/App.js
> +      let rsuInfoData = await axios.get(EnvironmentVars.getBaseApiUrl() + '/rsuinfo');
The "/rsuinfo" portion is already handled if we instead use `EnvironmentVars.rsuInfo`. Same can be applied to below endpoints.

2022-02-07 16:58 UTC, payneBrandon commented on cdot-web-app/src/components/Map.js
> +  function getStatus() {
Rather than relying on try/catch, which is costly when the error is thrown, let's add a check for the property to exist in the dictionary:

```
function getStatus() {
    return (selectedRsu.properties.Ipv4Address in props.rsuOnlineStatus) ?
      props.rsuOnlineStatus[selectedRsu.properties.Ipv4Address].current_status : "Offline";
  }
```

2022-02-07 16:58 UTC, payneBrandon commented on cdot-web-app/src/components/Map.js
> +  function isOnline() {
Same as below, let's re-write this to not rely on a try/catch but instead to check for the property existence before use:

```
function isOnline() {
    return (selectedRsu.properties.Ipv4Address in props.rsuOnlineStatus
      && props.rsuOnlineStatus[selectedRsu.properties.Ipv4Address].hasOwnProperty("last_online")) ?
      props.rsuOnlineStatus[selectedRsu.properties.Ipv4Address].last_online : "No Data";
  }
```

2022-02-16 23:55 UTC, mwodahl commented
Updated App.js to use environment vars. Replaced try/catch blocks to check for existence instead in map.js

2022-02-21 21:18 UTC, payneBrandon approved these changes
Looks good to me!

2022-02-21 21:18 UTC, merged