RSU Manager REST Auth and Proxy
CDOT-CV/RSU_Management pull request #40
Opened 2022-03-11 05:54 UTC by drewjj

This pull request is for the 2 cloud functions for calling RSU REST endpoints from the RSU Manager web application.
- rsu-rest-auth Cloud Function
  - cloud function that is public facing
  - Authorizes a Google OAuth2 JWT and then verifies if the user can run the requested command based on their role
  - Queries PostgreSQL DB for RSU SSH username and password if command requires it
  - Generates OAuth2 JWT for triggering the rsu-rest-proxy cloud function and passes on information needed to call the RSU REST directly
- rsu-rest-proxy Cloud Function
  - cloud function that is not public facing, requires Google OAuth2 token of GCP service accounts from the relative deployed GCP project that has the permissions to call it. 
  - Is connected to Kubernetes CDOT VPC
  - Interprets the information passed to it from rsu-rest-auth and sends HTTP requests to the K8s RSU REST deployment endpoint
 
Have fun reviewing this one :wink:

2022-03-11 23:43 UTC, payneBrandon requested changes
Just a couple minor questions. Looking very clean!

2022-03-11 23:43 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/README.md
> +- DB_HOST: The database's hostname or IP.
Can we add here that we expect a port to be included?

2022-03-11 23:43 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/rsu-proxies/rsu-rest-proxy/ssh_commands.py
> +    endpoint = f'http://{rest_endpoint}:5000/reboot'
Since we're passing sensitive information across the wire to this endpoint (username/password), we'll want to swap everything over to ssl in our next iteration.

2022-03-12 01:03 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/rsu-proxies/rsu-rest-auth/main.py
> +      'Access-Control-Allow-Methods': 'GET',
Yeah..I definitely have been copying my existing code for CORS support and didn't even think about this. Good catch.

2022-03-12 01:04 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/README.md
> +- DB_HOST: The database's hostname or IP.
Good point, probably useful for all the other times these env vars are used too.

2022-03-12 01:05 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/rsu-proxies/rsu-rest-proxy/ssh_commands.py
> +    endpoint = f'http://{rest_endpoint}:5000/reboot'
Oh you are right, I suppose I didn't think about it since we are within the VPC at this point.

2022-03-31 21:19 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/rsu-proxies/rsu-rest-proxy/ssh_commands.py
> +    endpoint = f'http://{rest_endpoint}:5000/reboot'
Separate PR next sprint will be fine here.

2022-03-31 22:51 UTC, payneBrandon approved these changes
Looks good to me!

2022-03-31 22:52 UTC, merged