RSU Manager Security Rework
CDOT-CV/RSU_Management pull request #42
Opened 2022-03-29 21:19 UTC by drewjj

This pull request was going to include all of the changes but since there are already existing pull requests I have the updates to the React app in the already existing React app pull request. I have the updates to the RSU REST Auth cloud function in that pull request.

This pull request includes a rework of the API Gateway into a cloud function. This also reworks the rsu-google-auth cloud function into the gateway cloud function instead of keeping it as a separate cloud function since user auth is a required part of the security rework.

I can upload a diagram for the security workflow if this is at all confusing.

2022-03-31 22:59 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/rsu-gateway/main.py
> +      'Access-Control-Allow-Methods': resources[request.path][0],
Clever!

2022-03-31 23:06 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/rsu-gateway/main.py
> +  elif resources[request.path][0] == 'POST':
We'll want an "else" case in here as well just in case someone tries to call with a "PUT" or "DELETE". Otherwise this will throw an exception when we try to return the "r.text" below.

2022-03-31 23:09 UTC, payneBrandon requested changes
Looking pretty solid here! We'll also want to update the README to reflect the change away from API Gateway in favor of this new solution.

2022-04-01 18:05 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/rsu-gateway/main.py
> +  elif resources[request.path][0] == 'POST':
Actually that should be caught on line 49 and anything not supported will be returned as an unsupported method type. (CORS will also catch this if this is attempted on a browser)

I can still add an else I suppose but it would actually never get run unless someone added a new endpoint for a method type that wasn't defined here at some point down the road.

2022-04-01 18:09 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/rsu-gateway/main.py
> +  elif resources[request.path][0] == 'POST':
Also, the reason why I didn't just make it as an else to return an unsupported method is because I wanted to have control over methods that may allow GETs, but not POSTs.

2022-04-01 18:13 UTC, drewjj commented on GCP_cloud_functions/rsu-manager/rsu-gateway/main.py
> +  elif resources[request.path][0] == 'POST':
As I think about it more, you could technically have two conditions that would combine the two - "if supported AND is a GET". But there's a lot of ways to refactor the same logic. If the way I implemented it is confusing I can do it this way too. I just wanted to handle the authorization before this step which I only wanted to handle in the scenario the request was supported first.

2022-04-01 20:41 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/rsu-gateway/main.py
> +  elif resources[request.path][0] == 'POST':
This makes sense, I just missed the check for supported verbs above.

2022-04-01 21:48 UTC, payneBrandon commented
> > Looking pretty solid here! We'll also want to update the README to reflect the change away from API Gateway in favor of this new solution.
> 
> Will do! Will add that with the diagram.

Will this be a part of this PR or no?

2022-04-04 18:34 UTC, drewjj commented
> > > Looking pretty solid here! We'll also want to update the README to reflect the change away from API Gateway in favor of this new solution.
> > 
> > 
> > Will do! Will add that with the diagram.
> 
> Will this be a part of this PR or no?

Yes! I just added it to the pull request.

2022-04-06 17:45 UTC, payneBrandon approved these changes
Looks good to me!

2022-04-06 17:45 UTC, merged