Add in static help page
CDOT-CV/RSU_Management pull request #44
Opened 2022-04-04 22:10 UTC by mwodahl

Help page contains useful information and images to aid users in operating the web app.

2022-04-06 15:55 UTC, payneBrandon requested changes
@mwodahl There looks to be a few merge conflicts we need to resolve before we can merge this one in.

2022-04-06 16:00 UTC, payneBrandon commented on cdot-web-app/src/components/Menu.js
> +              <Link to="/help" target="_blank" className='help'>
Since this whole count menu can be shown/hidden, let's pull this help link up to the top menu so it's always accessible.

2022-04-14 21:25 UTC, mwodahl commented on cdot-web-app/src/components/Menu.js
> +              <Link to="/help" target="_blank" className='help'>
Pulled this icon into the header

2022-04-14 21:27 UTC, mwodahl commented
Resolved merge conflict with main branch and added 'Help' to show when hovering over icon.

2022-04-14 21:35 UTC, payneBrandon approved these changes
Looks good to me!

2022-04-14 21:35 UTC, merged