removed print and added logging
CDOT-CV/RSU_Management pull request #47
Opened 2022-04-12 15:14 UTC by MohJumper

2022-04-12 16:15 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/rsu-proxies/rsu-rest-proxy/main.py
> +    logging.info("Credentials required but not provided")
Let's set this to error level

2022-04-18 15:47 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/rsu-proxies/rsu-rest-proxy/main.py
> +env_log_level = os.getenv("LOGING_LEVEL")
We'll want to have a corresponding `import os` statement above to allow interactions with that library.

2022-04-18 16:04 UTC, payneBrandon requested changes
A few comments, but getting closer!

2022-04-18 16:04 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +logging_levels = {
We can apply the same pattern for other setups below.

2022-04-18 16:04 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/test-count-emailer.py
> +import unittest
Should this class be in a separate PR/branch?

2022-04-18 17:40 UTC, MohJumper commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.INFO)
I did add checks to the environment level and then default to INFO if we can not find it.

2022-04-18 18:09 UTC, MohJumper commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/test-count-emailer.py
> +import unittest
I moved this class to a different branch.

2022-04-18 18:11 UTC, MohJumper commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +logging_levels = {
I changed all to the suggested code.

2022-04-18 18:27 UTC, payneBrandon commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +LOGGING_LEVEL = {
We can remove all these "LOGGING_LEVEL" dictionary definitions now that we aren't using them as well.

2022-04-18 18:29 UTC, payneBrandon requested changes
Just the one remaining issue. Otherwise looks good!

2022-04-18 19:39 UTC, MohJumper commented on GCP_cloud_functions/rsu-manager/rsu-count-emailer/main.py
> +LOGGING_LEVEL = {
Right! I removed them now.

2022-04-18 21:45 UTC, payneBrandon approved these changes
Looks good, thanks!

2022-04-18 21:46 UTC, merged